// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0zNl3T3yDwitKO0IZwsWftwYTfFl0XSk',
    appId: '1:113553278686:web:147706c779e1147893644f',
    messagingSenderId: '113553278686',
    projectId: 'gdc-hackathon-164be',
    authDomain: 'gdc-hackathon-164be.firebaseapp.com',
    storageBucket: 'gdc-hackathon-164be.firebasestorage.app',
    measurementId: 'G-FS5TVBTNTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8wGO87X0iImTS9DHJyJzg6qessWKqmY',
    appId: '1:113553278686:android:965b6868304c7ade93644f',
    messagingSenderId: '113553278686',
    projectId: 'gdc-hackathon-164be',
    storageBucket: 'gdc-hackathon-164be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbTd-6BaTvXgjnqUITYLEW5GGvu8yxJOM',
    appId: '1:113553278686:ios:4ee4c54885481a3c93644f',
    messagingSenderId: '113553278686',
    projectId: 'gdc-hackathon-164be',
    storageBucket: 'gdc-hackathon-164be.firebasestorage.app',
    iosBundleId: 'com.example.gdgHack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbTd-6BaTvXgjnqUITYLEW5GGvu8yxJOM',
    appId: '1:113553278686:ios:4ee4c54885481a3c93644f',
    messagingSenderId: '113553278686',
    projectId: 'gdc-hackathon-164be',
    storageBucket: 'gdc-hackathon-164be.firebasestorage.app',
    iosBundleId: 'com.example.gdgHack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0zNl3T3yDwitKO0IZwsWftwYTfFl0XSk',
    appId: '1:113553278686:web:76f68ed64536aa2f93644f',
    messagingSenderId: '113553278686',
    projectId: 'gdc-hackathon-164be',
    authDomain: 'gdc-hackathon-164be.firebaseapp.com',
    storageBucket: 'gdc-hackathon-164be.firebasestorage.app',
    measurementId: 'G-ELXQHS6K8K',
  );
}
